input_guardrails:
  - name: sensitive_data_check
    description: Check for sensitive information in input
    patterns:
      - pattern: \b(?:password|api_key|secret|token)\s*[:=]\s*\S+
        description: Prevents sharing of credentials and tokens
      - pattern: \b\d{16,19}\b
        description: Prevents sharing of credit card numbers
      - pattern: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
        description: Prevents sharing of email addresses

  - name: malicious_command_check
    description: Check for potentially malicious commands
    patterns:
      - pattern: (?:rm\s+-rf|mkfs|format|dd\s+if=/dev/zero)
        description: Prevents destructive system commands
      - pattern: (?:wget|curl)\s+.*\|\s*bash
        description: Prevents remote code execution
      - pattern: (?:eval|exec)\s*\(
        description: Prevents dynamic code execution

output_guardrails:
  - name: sensitive_data_sanitization
    description: Sanitize output to prevent information leakage
    patterns:
      - pattern: \b(?:password|api_key|secret|token)\s*[:=]\s*\S+
        description: Removes credentials and tokens from output
      - pattern: \b\d{16,19}\b
        description: Removes credit card numbers from output
      - pattern: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
        description: Removes email addresses from output 